### ISSUE TITLE
Icons for social media cover links in the sidebar

### ISSUE THREAD

**Issue by AlexandreDecan** [pooya-rostami/pooya-rostami.github.io#1]
Hello, 

Here's a screenshot explaining the issue: 

![Screenshot 2023-09-05 at 18-07-54 Pooya Rostami Mazrae - Home](https://github.com/pooya-rostami/pooya-rostami.github.io/assets/4992216/59d1ae36-c979-473f-9f4f-2027614a15b0)

This corresponds to the `.colorlib-footer` div object. It seems that its position is set to `absolute`, removing this constraint makes it better: 
```css
html body div.colorlib-footer {
  position: unset !important;
}
```
